2022-06-20 12:20:30,366 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2022-06-20 12:20:30,367 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'get_credentials']
2022-06-20 12:20:30,378 DEBUG    root            Running [gcloud.container.clusters.get-credentials] with arguments: [--project: "twingate-dev", NAME: "twingate-stg-relays-us-2 --zone us-central1-a"]
2022-06-20 12:20:30,379 DEBUG    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 113, in Run
    cluster, cluster_ref = _BaseRun(args, self.context)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 37, in _BaseRun
    location = location_get(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/command_lib/container/container_command_util.py", line 241, in GetZoneOrRegion
    raise calliope_exceptions.MinimumArgumentException(
googlecloudsdk.calliope.exceptions.MinimumArgumentException: One of [--zone, --region] must be supplied: Please specify location.
2022-06-20 12:20:30,379 ERROR    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
