2022-06-20 12:20:30,703 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters']
2022-06-20 12:20:30,705 DEBUG    root            Loaded Command Group: ['gcloud', 'container', 'clusters', 'get_credentials']
2022-06-20 12:20:30,716 DEBUG    root            Running [gcloud.container.clusters.get-credentials] with arguments: [--project: "twingate-dev", NAME: "twingate-dev-relays-us-1 --zone us-central1-b"]
2022-06-20 12:20:30,717 DEBUG    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 113, in Run
    cluster, cluster_ref = _BaseRun(args, self.context)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 37, in _BaseRun
    location = location_get(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/command_lib/container/container_command_util.py", line 241, in GetZoneOrRegion
    raise calliope_exceptions.MinimumArgumentException(
googlecloudsdk.calliope.exceptions.MinimumArgumentException: One of [--zone, --region] must be supplied: Please specify location.
2022-06-20 12:20:30,717 ERROR    root            (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.
